[case]
; mesh_file = /mesh/cav_1_20.cas
mesh_file = /mesh/cav_1_50_0.001.cas
; mesh_file = /mesh/cav_1_50_0.001.cas
; mesh_file = /mesh/cav_1_100_1e-4.cas
; mesh_file = 20.cas
; mesh_file = 40.cas
; mesh_file = 80.cas
output_dir = output

[solver]
uwall = 1
tauw = 0.0
delta = 1.0
St = 0.0

Nvx = 32
Nvy = 32
Nvz = 16
Lvx = 6.0
Lvy = 6.0
Lvz = 6.0

maxIter = 100
tol = 1e-5
printInterval = 1
checkInterval = 1

